//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class APPautocarpets: APPcarpets
{
	public APPautocarpets ()
	{
		APPLABEL.text = "auto-carpet-generator-by-3.14";

		/*
		APPLABEL.hidden = true;
		APPINSTRUCTION.hidden = true;
		APPFRAME.hidden = true;

		startx = 0;
		starty = 0;
		endx = SHGUI.current.resolutionX;
		endy = SHGUI.current.resolutionY;
		*/
	}

	float delay = 1f;
	public override void Update(){
		base.Update();

		delay -= Time.unscaledDeltaTime;
		if( delay < 0){
			delay = 1f;
			RegenerateCarpet();
		}
	}

	public override void ReactToInputKeyboard(SHGUIinput key){
		if (fadingOut)
			return;
		
		if (key == SHGUIinput.esc)
			SHGUI.current.PopView ();
		
		if (key == SHGUIinput.enter)
			SHGUI.current.PopView ();
	}
	
	public override void ReactToInputMouse(int x, int y, bool clicked, SHGUIinput scroll)
	{	
		if (fadingOut)
			return;
		
		if (clicked)
			SHGUI.current.PopView ();
	}
}


